Created search
campuscode-alumni/firma-shop pull request #5
Opened 2019-04-10 18:11 UTC by Eduhaydee

Foi executada a tarefa de criação da busca de anúncios.

2019-04-10 18:30 UTC, joaorsalmeida requested changes

2019-04-10 18:30 UTC, joaorsalmeida commented on app/controllers/home_controller.rb
> +    @sales_ads = current_user.company.sales_ads.all
Não precisa desse último `all` aqui :)

2019-04-10 18:30 UTC, joaorsalmeida commented on app/views/sales_ads/search.html.erb
> +	<p><%=  @sales_ads.count %></p>
Da pra melhorar essa usabilidade. Talvez uma frase mais completa como: `Encontramos X resultados ao buscar por 'o que a pessoa escreveu na busca' `

2019-04-10 18:30 UTC, joaorsalmeida commented on spec/features/user_search_sales_ad_spec.rb
> +    expect(page).to have_css('p', text: '2')
Aqui no teste refletir melhor como descrevi la em cima na view ;)

2019-04-11 00:49 UTC, HenriqueMorato approved these changes

2019-04-11 00:52 UTC, merged